name: zerops
channels:
  - anaconda
  - conda-forge
  - defaults
  - iopath
  - pytorch
dependencies:
  - fvcore=0.1.5.post20221221
  - iopath=0.1.9
  - jupyter=1.0.0
  - matplotlib=3.7.1
  - pycocotools=2.0.6
  - python=3.9.0
  - cudatoolkit=11.2
  - pytorch-gpu=1.9.0
  - scikit-learn=1.2.0
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - pip==23.0.1
  - numpy==1.23.5 
  - numpy-base==1.23.5
  - yacs==0.1.8
  - pip:
      - einops==0.6.1
      - ftfy==6.1.1
      - future==0.18.3
      - inflect==5.6.0
      - mkl-service==2.4.0
      - munkres==1.1.4
      - nltk==3.7
      - open3d==0.17.0
      - opencv-python==4.7.0.72
      - prettytable==3.7.0
      - tensorboardX==2.6
      - timm==0.9.2
      - transformers==4.30.1
      - bytecode==0.14.2

